version: "3.7"
services:
  app:
    build:
      args:
        user: fathur
        uid: 1000
      context: ./
      dockerfile: ./docker-local/Dockerfile
    image: cms-main
    container_name: cms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cms

  nginx:
    image: nginx:alpine
    container_name: cms-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-local/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - cms
  
  db:
    image: mysql:8
    container_name: cms-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: cms123
      MYSQL_USER: cms_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3381:3306
    volumes:
      - ./docker-local/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - cms

networks:
  cms:
    driver: bridge